version: 0.1.1.{build}
image: Visual Studio 2019

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- dotnet restore "StarlightResize/StarlightResize.csproj"

build_script:
- dotnet publish "StarlightResize/StarlightResize.csproj" -c Release

after_build:
- mv StarlightResize/bin/Release/net5.0-windows/win-x64/publish StarlightResize.%APPVEYOR_BUILD_VERSION%
- cp LICENSE.txt StarlightResize.%APPVEYOR_BUILD_VERSION%/
- cp README.md StarlightResize.%APPVEYOR_BUILD_VERSION%/README.txt
- 7z a StarlightResize.%APPVEYOR_BUILD_VERSION%.zip StarlightResize.%APPVEYOR_BUILD_VERSION%/* 

artifacts:
- path: StarlightResize.$(APPVEYOR_BUILD_VERSION).zip
